### ISSUE TITLE
Unexpected error handling settings file

### ISSUE THREAD

**Issue by threespoons** [RaunoT/plex-rewind#170]
### Plex Rewind Version

latest

### Description

once starting the docker from a compose yml receive the following error in the log: 
Settings File Not Found. Creating a new one.
error: unexpected error handling settings file

### Steps to reproduce

create docker from compose
docker starts
open browser to localhost:8383
error on page:
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1499927976

### Logs

```shell
date	stream	content
2024/07/24 15:08:46	stderr	}
2024/07/24 15:08:46	stderr	  digest: '1499927976'
2024/07/24 15:08:46	stderr	    at async _ (/app/.next/server/app/page.js:7:650) {
2024/07/24 15:08:46	stderr	    at a (/app/.next/server/app/page.js:8:1831)
2024/07/24 15:08:46	stderr	Error: Unexpected error handling settings file
2024/07/24 15:08:46	stderr	}
2024/07/24 15:08:46	stderr	  digest: '1499927976'
2024/07/24 15:08:46	stderr	    at async _ (/app/.next/server/app/page.js:7:650) {
2024/07/24 15:08:46	stderr	    at a (/app/.next/server/app/page.js:8:1831)
2024/07/24 15:08:46	stderr	Error: Unexpected error handling settings file
2024/07/24 15:08:46	stderr	}
2024/07/24 15:08:46	stderr	  digest: '131405523'
2024/07/24 15:08:46	stderr	    at async p (/app/.next/server/app/page.js:7:1996) {
2024/07/24 15:08:46	stderr	    at a (/app/.next/server/app/page.js:8:1831)
2024/07/24 15:08:46	stderr	Error: Unexpected error handling settings file
2024/07/24 15:08:46	stderr	Settings file not found. Creating a new one.
2024/07/24 15:08:46	stderr	Settings file not found. Creating a new one.
2024/07/24 15:05:04	stdout	 ✓ Ready in 412ms
2024/07/24 15:05:04	stdout	 ✓ Starting...
2024/07/24 15:05:04	stdout	
2024/07/24 15:05:04	stdout	  - Network:      http://0.0.0.0:8383
2024/07/24 15:05:04	stdout	  - Local:        http://localhost:8383
2024/07/24 15:05:04	stdout	  ▲ Next.js 14.2.5
```

### Platform

desktop

### Device

MacBook Air

### Operating System

Mac OS 15

### Browser and version

Safari

**Comment by hanm13** [comment]
You can fix this issue by setting the permissions of the config directory to 777

**Comment by stukinnear** [comment]
Not really a secure solution though is it.

**Comment by RaunoT** [comment]
re #144

**Comment by RaunoT** [comment]
@threespoons could you please try a clean install again with the image 
`ghcr.io/raunot/plex-rewind:ff727de22b33c3d3022623010260129e5afd28dd`

Unfortunately this issue has been going on for some time now. I am actively looking for a solution to it so any feedback/help is welcome.

**Comment by threespoons** [comment]
Sorry, issue still persists unfortunately.

**Comment by mduijm** [comment]
Hi,

the containers that are from Linuxserver use this setting in the docker file:
  environment:
      - PUID=1000
      - PGID=1000
I will try this and see if this works. Your container I hope will run then with my userid and groupid.

**Comment by mduijm** [comment]
too bad, that didn't do the trick. Perhaps check with team Linuxserver to see how they do it? Or ask them to create a container for you?

**Comment by RaunoT** [comment]
The settings file should automatically create itself into `config/settings.json` upon first running the application. If for some reason that doesn't seem to work. You could try manually creating the `settings.json` from [the example file](https://github.com/RaunoT/plex-rewind/blob/main/config/settings.example.json) before running the application.

Please let me know if this workaround works.

**Comment by PyroghostX** [comment]
I created the settings.json file and now it says: (normal docker on linux, not unraid)

Error: Unable to read the settings file!
    at i (/app/.next/server/app/page.js:8:2405)
    at async p (/app/.next/server/app/page.js:7:1990) {
  digest: '3221251093'


I have about 20 different docker containers running and none of them have had permission issues before, so i'm not sure what the problem is but has to be some way the app is running
And I have tried

**Comment by mduijm** [comment]
the problem is clear, the container is running with a userID and GroupID that is not on our systems, hence the need for chmod 777 to allow the application to write into the file. 

What the creator of the container should do is to be able to configure the GUID and the UUID to match a user on the host system, like other containers are doing. If that is done, this is no longer an issue.

**Comment by RaunoT** [comment]
Good insight @mduijm.

What I find interesting is that while @linuxserver images do mention:

> When using volumes (-v flags), permissions issues can arise between the host OS and the container, we avoid this issue by allowing you to specify the user PUID and group PGID.
> 
> Ensure any volume directories on the host are owned by the same user you specify and any permissions issues will vanish like magic.

And then specify in the docker-compose example

```
environment:
  - PUID=1000
  - PGID=1000
```

I don't see any reference to these in the [actual Dockerfile](https://github.com/linuxserver/docker-overseerr/blob/main/Dockerfile).

However, currently the [Docker image for Plex Rewind](https://github.com/RaunoT/plex-rewind/blob/develop/Dockerfile#L50C1-L51C39) does explicity set

```
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
```

And then assign permissions to those users.

That behaviour is taken from the [official Next.js Dockerfile example](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile), but perhaps it's not suited for this use case, as [I don't see Overseerr doing it](https://github.com/sct/overseerr/blob/develop/Dockerfile), despite also running on Next.js.

I tried removing any explicit permission setting in the image 
`ghcr.io/raunot/plex-rewind:cfaf13a481e39c8091db0946e34e630206308553`

@mduijm (and anyone else) could you please give this one a go, with and without setting PUID and PGID in the compose file like you did before?

**Comment by cliffordwhansen** [comment]
This is working for me but I used the preferred method[1] of `user` config in `docker-compose.yml`

```
services:
  plex-rewind:
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:8383
    env_file: '.env.local'
    volumes:
      - ./config:/app/config
```

I did try the `PUID`/`PGID` and not having any of these set and got permission denied

[1] https://docs.docker.com/compose/compose-file/05-services/#user

**Comment by RaunoT** [comment]
Good one @cliffordwhansen!

For anyone still running into this, please try setting your user/group id under the user parameter as instructed above in `docker-compose.yml`. I've removed the hardcoded user `nextjs` and group `nodejs` in `3.0.0-develop.3`

Here's an example compose file

```yml
services:
  plex-rewind:
    image: ghcr.io/raunot/plex-rewind:develop # :develop for the latest development version
    container_name: plex-rewind
    # user: 1000:1000 # change to your user and group id if you are running into permissions issues
    environment:
      - NEXTAUTH_SECRET= # (required) used to encrypt auth JWT token, generate one with `openssl rand -base64 32`
      - NEXTAUTH_URL=http://localhost:8383 # (required) change to your domain if you are exposing the app to the internet
      - NEXT_PUBLIC_SITE_URL=http://localhost:8383 # (required) change to your domain if you are exposing the app to the internet
      - NEXT_PUBLIC_STATISTICS_START_DATE=2018-01-01 # (optional) starting date for "all time" option (YYYY-MM-DD)
    volumes:
      - ./config:/app/config
    ports:
      - 8383:8383
    restart: unless-stopped
```

before

<img width="339" alt="image" src="https://github.com/user-attachments/assets/3866f8b6-fb14-41d8-b00a-f066bcac7add">


after

<img width="324" alt="image" src="https://github.com/user-attachments/assets/4af0c0c9-1eec-438c-976a-ee0d414abe93">
