### ISSUE TITLE
500 Internal Server Error when creating and starting fresh docker-compose install

### ISSUE THREAD

**Issue by eemmmmg** [RaunoT/plex-rewind#258]
### Plex Rewind Version

I assume latest, because I'm using the :latest docker-compose image, but this also occurs in :develop

### Description

I have created a fresh docker-compose.yml file.

```
services:
  plex-rewind:
    image: ghcr.io/raunot/plex-rewind:latest # :develop for the latest development version
    container_name: plex-rewind
    environment:
      - NEXTAUTH_SECRET=<<<redacted>>> # (required) used to encrypt auth JWT token, generate one with `openssl rand -base64 32`
      - NEXTAUTH_URL=http://<<<lan_ip>>>:8383 # (required) change to your domain if you are exposing the app to the internet
      - NEXT_PUBLIC_SITE_URL=http://<<<lan_ip>>>:8383 # (required) change to your domain if you are exposing the app to the internet
    volumes:
      - ./config:/app/config
    ports:
      - 8383:8383
    restart: unless-stopped
```

The actual container starts up, but when I go to http://<<<lan_ip>>>:8383 I got a white screen with just "500 | Internal Server Error" and I cannot proceed with setup at all.

### Steps to reproduce

Create docker-compose.yml file, fill out information according to documentation (secret, IP address (in my case it's a LAN IP since I haven't configured my subdomain yet), start with `docker-compose up -d` then go to the web page.

### Screenshots

![image](https://github.com/user-attachments/assets/cf100ba7-caa5-49e2-a0e7-2783c60b1432)

### Logs

```shell
plex-rewind  |   ▲ Next.js 14.2.13
plex-rewind  |   - Local:        http://localhost:8383
plex-rewind  |   - Network:      http://0.0.0.0:8383
plex-rewind  | 
plex-rewind  |  ✓ Starting...
plex-rewind  |  ✓ Ready in 55ms
plex-rewind  | Error: fetch failed
plex-rewind  |     at context.fetch (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/context.js:296:38)
plex-rewind  |     at Z.callbacks.authorized (/app/.next/server/src/middleware.js:2:10562)
plex-rewind  |     at /app/.next/server/src/middleware.js:3:889
plex-rewind  |     at l (/app/.next/server/src/middleware.js:3:579)
plex-rewind  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
plex-rewind  |     at async Object.t [as handler] (/app/.next/server/src/middleware.js:3:834)
plex-rewind  |     at async F (/app/.next/server/src/middleware.js:2:8414)
plex-rewind  |     at async /app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22
plex-rewind  |     at async runWithTaggedErrors (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
plex-rewind  |     at async NextNodeServer.runMiddleware (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:1062:24) {
plex-rewind  |   cause: ConnectTimeoutError: Connect Timeout Error
plex-rewind  |       at onConnectTimeout (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:9145:28)
plex-rewind  |       at eval (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:9101:50)
plex-rewind  |       at Immediate.eval [as _onImmediate] (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.13_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:655888), <anonymous>:9133:13)
plex-rewind  |       at process.processImmediate (node:internal/timers:483:21)
plex-rewind  |       at process.callbackTrampoline (node:internal/async_hooks:130:17) {
plex-rewind  |     code: 'UND_ERR_CONNECT_TIMEOUT'
plex-rewind  |   }
plex-rewind  | }
```

### Platform

desktop

### Device

My computer?

### Operating System

Server: Manjaro, Client/Desktop: Debian

### Browser and version

LibreWolf 130.0.1-1
